# Generated by Django 3.1.1 on 2020-09-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city_code',
            old_name='city_code',
            new_name='IATA',
        ),
    ]
