# Generated by Django 3.1.1 on 2020-09-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200928_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_info',
            name='models_type',
            field=models.CharField(default='tour', max_length=4),
        ),
    ]
