# Generated by Django 3.1.1 on 2020-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_leg1'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_comm', models.TextField()),
                ('exp1', models.TextField(null=True)),
                ('exp2', models.TextField(null=True)),
                ('exp3', models.TextField(null=True)),
            ],
        ),
    ]
