# Generated by Django 3.1.1 on 2020-09-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_comm', models.TextField()),
                ('exp1', models.TextField(null=True)),
                ('exp2', models.TextField(null=True)),
                ('exp3', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo')),
            ],
        ),
    ]
