# Generated by Django 3.1.1 on 2020-09-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
