# Generated by Django 3.1.1 on 2020-10-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_login_log_one_time_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='one_time_password',
            name='id',
        ),
        migrations.AddField(
            model_name='one_time_password',
            name='otp_id',
            field=models.CharField(default='O000', max_length=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
