# Generated by Django 3.1.1 on 2020-10-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201001_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='no_of_pass',
            field=models.IntegerField(default=1),
        ),
    ]
