# Generated by Django 3.1.1 on 2020-10-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201002_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_log',
        ),
    ]
