# Generated by Django 3.1.1 on 2020-10-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_login_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=6)),
                ('login_date_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='logout_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logout_date', models.DateTimeField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_log')),
            ],
        ),
    ]
