# Generated by Django 3.1.1 on 2020-10-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_login_log_logout_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortcuts',
            fields=[
                ('shortcut', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('abbri', models.CharField(max_length=200)),
            ],
        ),
    ]
