# Generated by Django 3.1.1 on 2020-10-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201022_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default='2020-01-01 12:00:00'),
        ),
    ]
