# Generated by Django 3.1.1 on 2020-10-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_comment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='total_price',
            field=models.FloatField(default=10246),
        ),
        migrations.AlterField(
            model_name='price',
            name='miles',
            field=models.IntegerField(default=10000),
        ),
    ]
